# ref: https://github.com/actions/runner-images
name: amd64 Linux Bazel

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  bzlmod:
    name: Linux•Bazel(bzlmod)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-cache: true
          disk-cache: ${{github.workflow}}
          repository-cache: true
      - name: Show Bazel version
        run: bazel version
      - name: Build
        run: bazel build --config=ci //...
      - name: Test
        run: bazel test --config=ci //...

  workspace:
    name: Linux•Bazel(workspace)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-cache: true
          disk-cache: ${{github.workflow}}
          repository-cache: true
      - name: Show Bazel version
        run: bazel version
      - name: Build
        run: >
          bazel build --config=ci
          --noenable_bzlmod --enable_workspace
          //...
      - name: Test
        run: >
          bazel test --config=ci
          --noenable_bzlmod --enable_workspace
          //...

  amd64_linux_bazel:
    runs-on: ubuntu-latest
    needs: [bzlmod, workspace]
    steps:
      - uses: actions/checkout@v6
